/// Flutter icons Groceryl
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Groceryl
///      fonts:
///       - asset: fonts/Groceryl.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Groceryl {
  Groceryl._();

  static const _kFontFam = 'Groceryl';
  static const String? _kFontPkg = null;

  static const IconData cart = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData category = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
